#!/usr/bin/env python3

from src import Snaky
from src import ValueHandler
from sys import exit
from sys import argv

def main() :
    handler = ValueHandler(argv)
    handler.set_up()
    snaky = Snaky(handler)
    return snaky.run()

if __name__ == "__main__":
    main()
